- hosts: localhost
  connection: local
  vars:
    helm_version: helm-v3.7.2
    helm_url: "https://get.helm.sh/{{ helm_version }}-linux-amd64.tar.gz"

  tasks:
    - include_vars:
        dir: vars/helm

    - name: Unarchive a file that needs to be downloaded (added in 2.0)
      become: yes
      ansible.builtin.unarchive:
        src: "{{ helm_url }}"
        dest: /tmp
        remote_src: yes
        include: linux-amd64/helm
      register: helm

    - name: Copy helm binary to /usr/local/bin
      become: yes
      copy:
        src: /tmp/linux-amd64/helm
        dest: /usr/local/bin
        mode: 0755

    - name: Install helm-diff plugin
      kubernetes.core.helm_plugin:
        plugin_path: "{{ helm_diff_url }}"
        state: present
