- hosts: localhost
  gather_facts: no
  tasks:
    - name: Include awx variables
      include_vars:
        dir: vars/awx

    - include_tasks: tasks/helm_preqreqs.yml

    - name: Create awx namespace
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ awx_namespace }}"

    - name: Restore awx volumes from backups
      longhorn_restore_backup:
        hostname: "{{ longhorn_hostname }}"
        replicas: 2
        match_pvc_names: "{{ match_pvc_names }}"
        validate_certs: no
      register: restore_result

    - name: Wait for restored volumes to be ready (detached state)
      longhorn_volume_wait:
        hostname: "{{ longhorn_hostname }}"
        validate_certs: no
        volume: "{{ item['volume'] }}"
        state: "detached"
      register: wait_result
      loop: "{{ restore_result.restored_backups }}"
      when: restore_result is defined

    - name: Re-query longhorn volumes if any were restored from backup
      longhorn_list_volumes:
        hostname: "{{ longhorn_hostname }}"
        validate_certs: no
        match_pvc_names: "{{ match_pvc_names }}"
      register: volumes_result

    - name: Create PersistentVolumes and PersistentVolumeClaims
      longhorn_create_pv_pvc:
        hostname: "{{ longhorn_hostname }}"
        validate_certs: no
        match_pvc_names: "{{ match_pvc_names }}"
      register: create_pv_pvc_result

