---
- name: Fetch kube config from master
  delegate_to: k3s-server-01
  ansible.builtin.fetch:
    src: ~/.kube/config
    dest: "{{ kube_config_path | mandatory }}"  
    flat: yes
    mode: "0600"

- name: Ensure secure mode on kube config
  ansible.builtin.file:
    path: "{{ kube_config_path | mandatory }}"
    mode: "0600"

