---
ansible_user: "{{ vault_ansible_user }}"
ansible_password: "{{ vault_ansible_password }}"
ansible_become_pass: "{{ vault_ansible_become_pass }}"

kube_config_src: "k3s-server-01"
kube_config_path: "{{ playbook_dir }}/kube/config"

files_path: "{{ playbook_dir }}/files"

